# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://sunying12.github.io/
title: Soaringsun Handyman Services
email: soaringsunlandscaping@live.com
author: Hui Sun
description: "Hui's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: file-pdf-o
    title: Gallery
    url: https://docs.google.com/presentation/d/1Q7_sBhAxxwc-gbN90hr1ObAeUX536q5bOE4qwtfdMnQ/edit?usp=sharing
  - icon: file-pdf-o
    title: Recent_Projects
    url: https://docs.google.com/presentation/d/1gLwobgHgBgA3nTztdiSqV7gEzJkF-qZs0jB9zVBnSko/edit?usp=sharing
  - icon: envelope-o
    title: Connect with me!
    url: mailto:soaringsunlandscaping@live.com



