# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://sunying12.github.io/
title: Ying Sun
email: sunyings@alumni.stanford.edu
author: Ying Sun
description: "Ying's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
#markdown: kramdown
#permalink: pretty
# Build sitemap
#gems:
#  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/sunyings/
  - icon: twitter
    title: twitter
    url: https://twitter.com/sunying12
  - icon: github
    title: github
    url: https://github.com/sunying12 
  - icon: file-pdf-o
    title: CV
    url: img/SunY_Resume_07.06.2020_consulting
  - icon: envelope-o
    title: Connect with me!
    url: mailto:sunyings@alumni.stanford.edu


